Repository NordicSemiconductor/pc-nrfconnect-cellularmonitor, pull requests merged in 2024-12, with the labels that each got.

#444 Replace single with double quotes in open "how to use"
  src/features/startup/startupDialog.tsx
Labels: doc not required, ui not required

#445 Certificate manager tab fixes
  Changelog.md
  package-lock.json
  package.json
  src/features/certificateManager/CertificateManager.tsx
  src/index.scss
Labels: doc required, ui required

#435 Feat/modem db 2.0.1
  Changelog.md
  resources/traceDB/config_v3.json
  resources/traceDB/mfw_nrf9160_1.3.6-FOTA-TEST_trace-db.json
  resources/traceDB/mfw_nrf9160_1.3.6_trace-db.json
  resources/traceDB/mfw_nrf9160_1.3.7-FOTA-TEST_trace-db.json
  resources/traceDB/mfw_nrf9160_1.3.7_trace-db.json
  resources/traceDB/mfw_nrf91x1_2.0.1-FOTA-TEST_trace-db.json
  resources/traceDB/mfw_nrf91x1_2.0.1_trace-db.json
  resources/traceDB/mfw_nrf91x1_2.0.2-FOTA-TEST_trace-db.json
  resources/traceDB/mfw_nrf91x1_2.0.2_trace-db.json
  src/features/SidePanel/DatabaseFileOverride.tsx
  src/features/programSample/programSample.ts
Labels: doc required, ui not required

#449 Fix links open in startup dialog
  src/features/startup/startupDialog.tsx
Labels: doc not required, ui not required

#450 Fix link to cert manager docs
  src/app/DocumentationSection.tsx
Labels: doc not required, ui not required
