Repository NordicSemiconductor/pc-nrfconnect-cellularmonitor, pull requests merged in 2024-11, with the labels that each got.

#441 Add release date and NCD min required ver
  Changelog.md
  package-lock.json
Labels: doc not required, ui not required

#442 Update NCD required ver
  package.json
Labels: doc not required, ui not required

#443 doc: rename app + other edits
  .github/workflows/zoomin-publish.yml
  README.md
  doc/docs/capturing.md
  doc/docs/index.md
  doc/docs/installing.md
  doc/docs/loading.md
  doc/docs/memfault_in_production.md
  doc/docs/overview.md
  doc/docs/preparing.md
  doc/docs/requirements.md
  doc/docs/revision_history.md
  doc/docs/troubleshooting.md
  doc/docs/viewing.md
  doc/docs/viewing_rtt.md
  doc/mkdocs.yml
  doc/zoomin/custom.properties
Labels: documentation, doc required

#446 .github: update zoomin.yml to use upload v4
  .github/workflows/zoomin.yml
Labels: documentation
